[project]
name = "breathvader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytelegrambotapi>=4.25.0",
    "python-telegram-bot>=21.10",
]
